### ISSUE TITLE
Long pages break footer display

### ISSUE THREAD

**Issue by TAMHAN** [eustasy/jQuery.downBoy#1]
Hello,
I am working on a list of jQuery plug-ins for a British magazine, and think that I stumbled across a small oddity. Please run this code in a browser of choice:

```
<html>
<body>
    <script src="jquery-2.1.4.js"></script> 
    <script src="jquery.downboy.js"></script> 
    <script>
        $( document ).ready(function() {
            var innerHtml="Lorem Ipsum sic . . .<br>";
            for(i=0;i<7;i++){innerHtml+=innerHtml;}
            $( "#myFill" ).html(innerHtml);
        });
    </script>
<script>
    $(function() {
        downBoy('#myFooter'); // Run on load
        window.onresize = function() { // On Resize
            downBoy('#myFooter'); // Run Again
        };
    });
</script>
    <div id="myFill"></div>

    <div id="myFooter" style="background-color: yellow;"><h1>This is a footer</h1></div>
</body>
</html>
```

You will see that the footer "floats" off as the user scrolls down...

With compliments
Tam

**Comment by lewisgoddard** [comment]
Since your code doesn't include a DocType, you are forcing the browser to render using quirks mode, which assumes window height is always large than document height, among other things. downBoy detects that incorrect return and thinks that it needs to reposition to footer, even though it doesn't. [1]

Adding `<!DocType html>` at the start of your file should fix things for you.
1. http://stackoverflow.com/questions/12103208/jquery-window-height-is-returning-the-document-height

**Comment by TAMHAN** [comment]
Hello,
big thanks for your help!

Tam
